#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -f composer.lock ]
then
	CHANGED=`git diff $1 $2 --stat -- $GIT_DIR/../composer.lock | wc -l`
	if [ $CHANGED -gt 0 ];
	then
            echo -e "${RED}Composer.lock has changed. You must run composer install!${NC}"
        fi
fi