#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color

CHANGED=`git diff HEAD@{1} --stat -- "$(git rev-parse --show-toplevel)/composer.lock" | wc -l`
if [ $CHANGED -gt 0 ];
then
	echo -e "${RED}Composer.lock has changed. You must run composer install!${NC}"
fi